baseURL = "/"
languageCode = "en"
DefaultContentLanguage = "en"
theme = "simpleness"

title = "Simple BLOG"
enableInlineShortcodes = true
enableEmoji = true
googleAnalytics = ""

[params]
  lazyImage = true
  enableMathJax = false # enable it in Front Matter
  enableReadingTime = true
  favicon = "favicon.ico"
  startyear = "2019"
  description = "Hi, Big BOSS."
  disqus = ""
  mainSections = "kubernetes"

[params.valine]
  enable = false
  lang = 'en' # zh-CN
  appId = ''
  appKey = ''
  placeholder = 'What should I say......'
  requiredFields = ['nick', 'mail']
  avatar = 'robohash'
  visitor = true
  serverURLS = 'https://blog.hchen.xyz'
  debug = false # display the visitor counts when using 'hugo server'

[menu]
  [[menu.main]]
  name = "Home"
  url = "/post"
  weight = 1
  [[menu.main]]
  name = "Kubernetes"
  url = "/kubernetes/"
  weight = 2
  [[menu.main]]
  name = "About"
  url = "/page/about/"
  weight = 3
  [[menu.main]]
  name = "Contact"
  url = "/page/contact/"
  weight = 4

[social]
  github = "https://github.com/RainerChiang"
  rss = "index.xml"

[taxonomies]
category = "categories"
tag = "tags"

# doc: https://gohugo.io/getting-started/configuration-markup#highlight
# syntax style: https://xyproto.github.io/splash/docs/longer/all.html
[markup]
  [markup.highlight]
    guessSyntax = true
    hl_Lines = ""
    # lineNoStart = 1
    # lineNos = true
    # lineNumbersInTable = true
    noClasses = true
    style = "monokai" # github, dracula, vim, monokai
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 1
    